---
awair:
  address: https://developer-apis.awair.is
  token: eyJ0eXA... copy this from AWAIR app. See README.md

pw:
  username: yourusername@gmail.com
  password: yourpassword


### The following are probably ok for you to leave alone

logging:
  level:
    org.springframework.web: ERROR
    ROOT: INFO

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      accept-single-value-as-array: true


resilience4j.retry:
  configs:
    default:
      maxAttempts: 4       # Retry 4 times, 1 minute apart
      waitDuration: 60000
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
        - feign.FeignException.InternalServerError
