keycloak:
  auth-server-url: https://login.planetwatch.io/auth
  realm: Planetwatch
  resource: external-login
  public-client: true
  enable-basic-auth: false


spring:
  main:
    allow-circular-references: true